I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scene_walkOut.rpy", line 23, in script
    empty ""
ScriptError: could not find label 'telplay'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Informatique\Documents\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Informatique\Documents\renpy-8.0.3-sdk\renpy\main.py", line 660, in main
    run(restart)
  File "C:\Users\Informatique\Documents\renpy-8.0.3-sdk\renpy\main.py", line 146, in run
    renpy.execution.run_context(True)
  File "C:\Users\Informatique\Documents\renpy-8.0.3-sdk\renpy\execution.py", line 938, in run_context
    context.run()
  File "game/scene_walkOut.rpy", line 23, in script
    empty ""
  File "C:\Users\Informatique\Documents\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'telplay'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
OKDATA 1.0
Tue Oct 10 10:16:33 2023
