I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scene_walkOut.rpy", line 22, in script
    empty ""
ScriptError: could not find label 'telplay'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/scene_walkOut.rpy", line 22, in script
    empty ""
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'telplay'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
OKDATA 1.0
Thu Nov 23 11:15:06 2023
