I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script
    define medBubble = Character(None, None, kind=bubble)   # Lucy
  File "game/script.rpy", line 18, in <module>
    define medBubble = Character(None, None, kind=bubble)   # Lucy
TypeError: Character() got multiple values for argument 'kind'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 18, in script
    define medBubble = Character(None, None, kind=bubble)   # Lucy
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 18, in <module>
    define medBubble = Character(None, None, kind=bubble)   # Lucy
TypeError: Character() got multiple values for argument 'kind'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
OKDATA 1.0
Wed Nov  8 11:18:37 2023
